version: "2"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - "pgsql_data:/data/db"
    environment:
        - POSTGRES_USER=backend
        - POSTGRES_PASSWORD=1234567890
        - POSTGRES_DB=bookshop
    restart: always
    networks:
      - default

volumes:
  pgsql_data:
    driver: local